version: '3'

services:
  influxdb:
    image: influxdb:2.5-alpine
    env_file:
      - influxdb/influxdb.env
    volumes:
      - influxdb-vol:/var/lib/influxdb2:rw
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:9.3.1
    depends_on:
      - influxdb
    env_file:
      - influxdb/influxdb.env
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    restart: on-failure
    ports:
      - "3000:3000"
  telegraf:
    image: telegraf:1.24-alpine
    depends_on:
      - influxdb
    env_file:
      - influxdb/influxdb.env
    restart: on-failure:5
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  ds_price:
    build: ./ds-price/
    depends_on:
      - influxdb
    env_file:
      - influxdb/influxdb.env
    environment:
      DSCOLLECT_BUCKET_NAME: price
    restart: on-failure

volumes:
  influxdb-vol:
